### ISSUE TITLE
CI failed with parsing a DOI

### ISSUE THREAD

**Issue by astrochun** [pulibrary/dspace-osti#68]
Unclear why this is happening, but it seems to have issue with the DOE DOI from what I can tell:
https://github.com/pulibrary/dspace-osti/runs/8133625045?check_suite_focus=true

```python
Run python Scraper.py
  python Scraper.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.13/x64
Pulled 177 records from OSTI.
countItems:  181
all_items:  181
Pulled 181 records from DSpace.
Traceback (most recent call last):
  File "Scraper.py", line 255, in <module>
    s.run_pipeline()
  File "Scraper.py", line 245, in run_pipeline
    self.get_unposted_metadata()
  File "Scraper.py", line 145, in get_unposted_metadata
    osti_handles = [get_handle(record['doi'], redirects_j)
  File "Scraper.py", line 145, in <listcomp>
    osti_handles = [get_handle(record['doi'], redirects_j)
  File "Scraper.py", line 129, in get_handle
    assert r.status_code == 200, f"Error parsing DOI: {doi}"
AssertionError: Error parsing DOI: https://doi.org/10.11578/1814956
Error: Process completed with exit code 1.
```
﻿

**Comment by astrochun** [comment]
As it turns out, there was a temporary issue with DataCite/DOE such that a non-200 response was provided. Re-running GitHub Actions fixed the issue
